version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: pnpm dev --filter 'commerce-template'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development