export const branchCategories = [
  { value: "africana", label: "Africana" },
  { value: "bebicas-alcoholicas", label: "Bebicas Alcoholicas" },
  { value: "argentina", label: "Argentina" },
  { value: "asiatica", label: "Asiatica" },
  { value: "panadería", label: "Panadería" },
  { value: "panadería-y-pastelería", label: "Panadería y Pastelería" },
  { value: "comida-de-bar", label: "Comida de bar" },
  { value: "barbacoa", label: "Barbacoa" },
  { value: "brasileña", label: "Brasileña" },
  { value: "desayuno-bruch", label: "Desayuno Bruch" },
  { value: "te-de-burbujas", label: "Te de burbujas" },
  { value: "hamburguesas", label: "Hamburguesas" },
  { value: "burritos", label: "Burritos" },
  { value: "cajún", label: "Cajún" },
  { value: "pastel", label: "Pastel" },
  { value: "caribeña", label: "Caribeña" },
  { value: "pollo", label: "Pollo" },
  { value: "chilena", label: "Chilena" },
  { value: "china", label: "China" },
  { value: "cafe-y-te", label: "Cafe y Te" },
  { value: "colombiana", label: "Colombiana" },
  { value: "crepas-o-crepería", label: "Crepas o Crepería" },
  { value: "postres", label: "Postres" },
  { value: "ecuatoriana", label: "Ecuatoriana" },
  { value: "egipcia", label: "Egipcia" },
  { value: "empanadas", label: "Empanadas" },
  { value: "europea", label: "Europea" },
  { value: "filipina", label: "Filipina" },
  { value: "pescado-frito-c/-papas", label: "Pescado Frito C/ papas" },
  { value: "pescado-y-mariscos", label: "Pescado y Mariscos" },
  { value: "francés", label: "Francés" },
  { value: "alemana", label: "Alemana" },
  { value: "gourmet", label: "Gourmet" },
  { value: "griega", label: "Griega" },
  { value: "guatemalteca", label: "Guatemalteca" },
  { value: "halal", label: "Halal" },
  { value: "hawaiana", label: "Hawaiana" },
  { value: "saludable", label: "Saludable" },
  { value: "helado-y-yogurt", label: "Helado y Yogurt" },
  { value: "india", label: "India" },
  { value: "indionesia", label: "Indionesia" },
  { value: "israelí", label: "Israelí" },
  { value: "italiana", label: "Italiana" },
  { value: "japonesa", label: "Japonesa" },
  { value: "ramen", label: "Ramen" },
  { value: "sushi", label: "Sushi" },
  { value: "jugos-y-licuados", label: "Jugos y Licuados" },
  { value: "kebab", label: "Kebab" },
  { value: "coreana", label: "Coreana" },
  { value: "kosher", label: "Kosher" },
  { value: "libanesa", label: "Libanesa" },
  { value: "malasia", label: "Malasia" },
  { value: "mediterránea", label: "Mediterránea" },
  { value: "mexicana", label: "Mexicana" },
  { value: "medio-oriente", label: "Medio Oriente" },
  { value: "australiana-moderna", label: "Australiana moderna" },
  { value: "marroquí", label: "Marroquí" },
  { value: "paquistaní", label: "Paquistaní" },
  { value: "peruana", label: "Peruana" },
  { value: "pizza", label: "Pizza" },
  { value: "poke", label: "Poke" },
  { value: "portuguesa", label: "Portuguesa" },
  { value: "rusa", label: "Rusa" },
  { value: "ensaladas/sandwiches", label: "Ensaladas/sandwiches" },
  { value: "mariscos", label: "Mariscos" },
  { value: "bocadillos", label: "Bocadillos" },
  { value: "sureña", label: "Sureña" },
  { value: "española", label: "Española" },
  { value: "carnes-a-la-parrilla", label: "Carnes a la parrilla" },
  { value: "tacos", label: "Tacos" },
  { value: "tex-mex", label: "Tex-Mex" },
  { value: "tailandesa", label: "Tailandesa" },
  { value: "turca", label: "Turca" },
  { value: "vegetariana-vegana", label: "Vegetariana-Vegana" },
  { value: "venezolana", label: "Venezolana" },
  { value: "vietnamita", label: "Vietnamita" },
  { value: "alitas", label: "Alitas" },
  { value: "otro", label: "Otro" },
];
